### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED error when building ui

### ISSUE THREAD

**Issue by slavas490** [ProxeusApp/proxeus-core#366]
### Subject of the issue
Unable to run ui part (using make ui-dev command) because of this issue:
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/slavas490/Documents/work/proxeus-core/ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/slavas490/Documents/work/proxeus-core/ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/slavas490/Documents/work/proxeus-core/ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/slavas490/Documents/work/proxeus-core/ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/slavas490/Documents/work/proxeus-core/ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/slavas490/Documents/work/proxeus-core/ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/slavas490/Documents/work/proxeus-core/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/slavas490/Documents/work/proxeus-core/ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/slavas490/Documents/work/proxeus-core/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/slavas490/Documents/work/proxeus-core/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/slavas490/Documents/work/proxeus-core/ui/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
This problem appears only while using node.js > 16 version

### Your environment
macOS Ventura  13.4.1
Node.js v20.7.0

### Steps to reproduce
run this command:
`$ make ui-dev`

**Comment by loleg** [comment]
Currently Node 18+ are _not_ supported. We will open a separate issue to look into upgrading our dependencies.

**Comment by loleg** [comment]
See  #452 for progress on updating Node version.
